"""add idle tracking

Revision ID: 685ecbcf8095
Revises: ae89c887d5e1
Create Date: 2026-10-06 09:49:15.521509

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "685ecbcf8095"
down_revision = "ae89c887d5e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pcs", sa.Column("is_idle", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column("usage_daily", sa.Column("idle_seconds", sa.Integer(), server_default=sa.text("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_daily", "idle_seconds")
    op.drop_column("pcs", "is_idle")
    # ### end Alembic commands ###
