"""add manual_lock_until to pcs

Revision ID: a66939479621
Revises: a9d967617f12
Create Date: 2026-08-20 12:25:52.557333

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a66939479621"
down_revision = "a9d967617f12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pcs", sa.Column("manual_lock_until", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pcs", "manual_lock_until")
    # ### end Alembic commands ###
