"""add bonus_seconds and day_limits

Revision ID: ae89c887d5e1
Revises: a66939479621
Create Date: 2026-10-04 14:12:35.148273

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ae89c887d5e1"
down_revision = "a66939479621"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pcs",
        sa.Column(
            "day_limits",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column("usage_daily", sa.Column("bonus_seconds", sa.Integer(), server_default=sa.text("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_daily", "bonus_seconds")
    op.drop_column("pcs", "day_limits")
    # ### end Alembic commands ###
