"""init

Revision ID: 0e8d5a061178
Revises: 
Create Date: 2026-08-19 11:42:11.072738

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0e8d5a061178"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pcs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("daily_limit_minutes", sa.Integer(), nullable=False),
        sa.Column("warning_before_lock_seconds", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("lock_reason", sa.String(length=64), nullable=True),
        sa.Column("desired_locked", sa.Boolean(), nullable=False),
        sa.Column("desired_lock_reason", sa.String(length=64), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_command_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_active_user", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pcs_name"), "pcs", ["name"], unique=True)
    op.create_table(
        "command_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pc_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["pc_id"], ["pcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_command_logs_action"), "command_logs", ["action"], unique=False)
    op.create_index(op.f("ix_command_logs_pc_id"), "command_logs", ["pc_id"], unique=False)
    op.create_table(
        "pc_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pc_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["pc_id"], ["pcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pc_events_event_type"), "pc_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_pc_events_pc_id"), "pc_events", ["pc_id"], unique=False)
    op.create_table(
        "schedule_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pc_id", sa.Integer(), nullable=False),
        sa.Column("days", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("allowed_from", sa.Time(), nullable=False),
        sa.Column("allowed_until", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["pc_id"], ["pcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedule_slots_pc_id"), "schedule_slots", ["pc_id"], unique=False)
    op.create_table(
        "usage_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pc_id", sa.Integer(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("active_seconds", sa.Integer(), nullable=False),
        sa.Column("locked_seconds", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["pc_id"], ["pcs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pc_id", "usage_date", name="uq_usage_daily_pc_date"),
    )
    op.create_index(op.f("ix_usage_daily_pc_id"), "usage_daily", ["pc_id"], unique=False)
    op.create_index(op.f("ix_usage_daily_usage_date"), "usage_daily", ["usage_date"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_daily_usage_date"), table_name="usage_daily")
    op.drop_index(op.f("ix_usage_daily_pc_id"), table_name="usage_daily")
    op.drop_table("usage_daily")
    op.drop_index(op.f("ix_schedule_slots_pc_id"), table_name="schedule_slots")
    op.drop_table("schedule_slots")
    op.drop_index(op.f("ix_pc_events_pc_id"), table_name="pc_events")
    op.drop_index(op.f("ix_pc_events_event_type"), table_name="pc_events")
    op.drop_table("pc_events")
    op.drop_index(op.f("ix_command_logs_pc_id"), table_name="command_logs")
    op.drop_index(op.f("ix_command_logs_action"), table_name="command_logs")
    op.drop_table("command_logs")
    op.drop_index(op.f("ix_pcs_name"), table_name="pcs")
    op.drop_table("pcs")
    # ### end Alembic commands ###
